### PR TITLE
fix: handle empty xml updates

### LINKED ISSUE #34: Filter out "empty" XML files
When adding or updating files, filter and remove `xml` files that have no localizable strings. For minimum viable product (MVP), find any matches for the XPaths specified in translatable_elements, if any. Bonus points for checking that the specified attributes and elements have content.

### PR DESCRIPTION
**Pull request by cnaples79**
## Summary
- ensure XML filtering checks for actual content and applies when type is set to xml even without .xml extension
- during update, delete previously uploaded files that are now non-localizable so Crowdin doesn’t retain empty XML

## Rationale
Issue #34 requested filtering empty XML uploads and handling the remaining edge case where updated files lose translatable content.

## Changes
- XmlFilter now treats XPath matches with blank elements/attributes as non-localizable and honors config type=xml
- Collect non-localizable matches during update and delete corresponding existing Crowdin files
- Added regression tests for XML content checks, type-based filtering, and update-time deletion

## Test Plan
- Not run (per request)

Fixes #34

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/overcrowdin/67)

### CODE REVIEW

File: src/Overcrowdin/UpdateCommand.cs [hunk 1]
```diff
@@ -49,6 +50,15 @@ public static async Task<int> UpdateFilesInCrowdin(IConfiguration config, Option
 				}
 			} while (++i < updateFileParametersList.Count);
```
Comment (papeh) [inline src/Overcrowdin/UpdateCommand.cs]:
```
if (updateFileParametersList.Any())
{
    Console.WriteLine($"Updating...
```

**Review by papeh — CHANGES_REQUESTED** [review]
Thank you for submitting our first external pull request! Nice work overall. A few comments.

**Review by papeh — APPROVED** [review]
